# Generated by Django 5.2.7 on 2026-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_student_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Vikaspuri', 'Vikaspuri'), ('Pitampura', 'Pitampura'), ('South Ex', 'South Ex'), ('Noida', 'Noida'), ('Gurgaon', 'Gurgaon'), ('Ghaziabad', 'Ghaziabad')], default='Vikaspuri', max_length=50),
        ),
    ]
