# Generated by Django 5.2.7 on 2026-04-12 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_batch_id_alter_trainer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_sid', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='dashboard.batch')),
            ],
            options={
                'unique_together': {('batch', 'student_sid', 'date')},
            },
        ),
    ]
