# Generated by Django 5.2.7 on 2026-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_batch_id_alter_dailyattendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
