# Generated by Django 5.2.7 on 2026-05-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_batch_id_alter_dailyattendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
