# Generated by Django 5.2.7 on 2026-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_batch_options_alter_batch_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='branch',
            field=models.CharField(choices=[('Vikaspuri', 'Vikaspuri'), ('Pitampura', 'Pitampura'), ('South Ex', 'South Ex'), ('Noida', 'Noida'), ('Gurgaon', 'Gurgaon'), ('Ghaziabad', 'Ghaziabad')], default='Vikaspuri', max_length=50),
        ),
    ]
