# Generated by Django 5.2.7 on 2026-05-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_trainer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default='OTHERS', max_length=100),
        ),
    ]
